import { db } from '@/db';
import { bookings } from '@/db/schema';

async function main() {
    const sampleBookings = [
        // Confirmed bookings (5 records)
        {
            listingId: 5,
            userId: 2,
            checkInDate: new Date('2025-02-10').toISOString(),
            checkOutDate: new Date('2025-02-15').toISOString(),
            numNights: 5,
            subtotal: 60000,
            tax: 6000,
            total: 66000,
            status: 'confirmed',
            paymentMethod: 'credit_card',
            refundedAt: null,
            createdAt: new Date('2025-01-25T10:30:00').toISOString(),
        },
        {
            listingId: 15,
            userId: 3,
            checkInDate: new Date('2025-02-18').toISOString(),
            checkOutDate: new Date('2025-02-22').toISOString(),
            numNights: 4,
            subtotal: 72000,
            tax: 7200,
            total: 79200,
            status: 'confirmed',
            paymentMethod: 'debit_card',
            refundedAt: null,
            createdAt: new Date('2025-01-26T14:15:00').toISOString(),
        },
        {
            listingId: 23,
            userId: 4,
            checkInDate: new Date('2025-03-05').toISOString(),
            checkOutDate: new Date('2025-03-12').toISOString(),
            numNights: 7,
            subtotal: 161000,
            tax: 16100,
            total: 177100,
            status: 'confirmed',
            paymentMethod: 'paypal',
            refundedAt: null,
            createdAt: new Date('2025-01-27T09:45:00').toISOString(),
        },
        {
            listingId: 42,
            userId: 5,
            checkInDate: new Date('2025-02-25').toISOString(),
            checkOutDate: new Date('2025-02-28').toISOString(),
            numNights: 3,
            subtotal: 151200,
            tax: 15120,
            total: 166320,
            status: 'confirmed',
            paymentMethod: 'credit_card',
            refundedAt: null,
            createdAt: new Date('2025-01-28T16:20:00').toISOString(),
        },
        {
            listingId: 8,
            userId: 2,
            checkInDate: new Date('2025-03-15').toISOString(),
            checkOutDate: new Date('2025-03-21').toISOString(),
            numNights: 6,
            subtotal: 57600,
            tax: 5760,
            total: 63360,
            status: 'confirmed',
            paymentMethod: 'debit_card',
            refundedAt: null,
            createdAt: new Date('2025-01-29T11:00:00').toISOString(),
        },
        // Pending bookings (3 records)
        {
            listingId: 8,
            userId: 2,
            checkInDate: new Date('2025-02-28').toISOString(),
            checkOutDate: new Date('2025-03-03').toISOString(),
            numNights: 3,
            subtotal: 28800,
            tax: 2880,
            total: 31680,
            status: 'pending',
            paymentMethod: 'credit_card',
            refundedAt: null,
            createdAt: new Date('2025-01-30T13:45:00').toISOString(),
        },
        {
            listingId: 34,
            userId: 3,
            checkInDate: new Date('2025-03-08').toISOString(),
            checkOutDate: new Date('2025-03-13').toISOString(),
            numNights: 5,
            subtotal: 204000,
            tax: 20400,
            total: 224400,
            status: 'pending',
            paymentMethod: 'paypal',
            refundedAt: null,
            createdAt: new Date('2025-01-30T15:20:00').toISOString(),
        },
        {
            listingId: 56,
            userId: 4,
            checkInDate: new Date('2025-03-20').toISOString(),
            checkOutDate: new Date('2025-03-24').toISOString(),
            numNights: 4,
            subtotal: 268800,
            tax: 26880,
            total: 295680,
            status: 'pending',
            paymentMethod: 'debit_card',
            refundedAt: null,
            createdAt: new Date('2025-01-31T08:30:00').toISOString(),
        },
        // Cancelled bookings (4 records)
        {
            listingId: 12,
            userId: 5,
            checkInDate: new Date('2025-01-20').toISOString(),
            checkOutDate: new Date('2025-01-25').toISOString(),
            numNights: 5,
            subtotal: 72000,
            tax: 7200,
            total: 79200,
            status: 'cancelled',
            paymentMethod: 'credit_card',
            refundedAt: null,
            createdAt: new Date('2025-01-10T10:15:00').toISOString(),
        },
        {
            listingId: 28,
            userId: 2,
            checkInDate: new Date('2025-02-05').toISOString(),
            checkOutDate: new Date('2025-02-08').toISOString(),
            numNights: 3,
            subtotal: 100800,
            tax: 10080,
            total: 110880,
            status: 'cancelled',
            paymentMethod: 'paypal',
            refundedAt: null,
            createdAt: new Date('2025-01-15T14:30:00').toISOString(),
        },
        {
            listingId: 47,
            userId: 3,
            checkInDate: new Date('2025-02-12').toISOString(),
            checkOutDate: new Date('2025-02-16').toISOString(),
            numNights: 4,
            subtotal: 225600,
            tax: 22560,
            total: 248160,
            status: 'cancelled',
            paymentMethod: 'debit_card',
            refundedAt: null,
            createdAt: new Date('2025-01-18T16:45:00').toISOString(),
        },
        {
            listingId: 19,
            userId: 4,
            checkInDate: new Date('2025-03-01').toISOString(),
            checkOutDate: new Date('2025-03-04').toISOString(),
            numNights: 3,
            subtotal: 68400,
            tax: 6840,
            total: 75240,
            status: 'cancelled',
            paymentMethod: 'credit_card',
            refundedAt: null,
            createdAt: new Date('2025-01-22T12:00:00').toISOString(),
        }
    ];

    await db.insert(bookings).values(sampleBookings);
    
    console.log('✅ Bookings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});