import { db } from '@/db';
import { listings } from '@/db/schema';

async function main() {
    const featuredPositions = new Set([0, 2, 4, 7, 9, 11, 14, 17]);
    
    const sampleListings = [
        {
            title: 'Modern Downtown Studio',
            description: 'Experience urban living at its finest in this sleek downtown studio. Located in the heart of the city, this contemporary space features floor-to-ceiling windows with stunning city views, a fully equipped kitchenette, and premium furnishings. Walking distance to restaurants, shopping, and entertainment venues. Perfect for business travelers or couples seeking a vibrant city experience.',
            pricePerNight: 85,
            numGuests: 2,
            numBedrooms: 0,
            numBeds: 1,
            numBathrooms: 1,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
                'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800'
            ]),
            userId: 1,
            status: 'available',
            featured: 1,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            title: 'Cozy Mountain Cabin Retreat',
            description: 'Escape to this charming mountain cabin nestled in the pines. This rustic yet comfortable retreat offers two bedrooms, a stone fireplace, and a wraparound deck with breathtaking mountain views. Enjoy hiking trails right from your doorstep, stargazing at night, and complete tranquility. Ideal for nature lovers and those seeking a peaceful getaway from city life.',
            pricePerNight: 120,
            numGuests: 4,
            numBedrooms: 2,
            numBeds: 3,
            numBathrooms: 2,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800',
                'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=800',
                'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800',
                'https://images.unsplash.com/photo-1464146072230-91cabc968266?w=800'
            ]),
            userId: 2,
            status: 'available',
            featured: 0,
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-01-08').toISOString(),
        },
        {
            title: 'Luxury Beachfront Villa',
            description: 'Indulge in paradise at this stunning beachfront villa with direct beach access. This luxurious property features five spacious bedrooms, a private infinity pool, gourmet kitchen, and expansive outdoor living areas. Wake up to ocean views, enjoy sunset cocktails on your terrace, and fall asleep to the sound of waves. Perfect for families or groups seeking an unforgettable beach vacation with premium amenities and unparalleled comfort.',
            pricePerNight: 450,
            numGuests: 10,
            numBedrooms: 5,
            numBeds: 6,
            numBathrooms: 4,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
                'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'
            ]),
            userId: 3,
            status: 'available',
            featured: 1,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            title: 'Charming Historic Townhouse',
            description: 'Step back in time while enjoying modern comforts in this beautifully restored Victorian townhouse. Located in a historic neighborhood, this three-bedroom home features original hardwood floors, decorative fireplaces, and period details throughout. The modern kitchen and updated bathrooms provide contemporary convenience. Walk to local cafes, boutiques, and museums. Ideal for history enthusiasts and families.',
            pricePerNight: 165,
            numGuests: 6,
            numBedrooms: 3,
            numBeds: 4,
            numBathrooms: 2,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800'
            ]),
            userId: 4,
            status: 'available',
            featured: 1,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'Minimalist Loft Apartment',
            description: 'Discover urban sophistication in this open-concept loft apartment. High ceilings, exposed brick walls, and industrial-chic design create a unique living space. The modern kitchen features stainless steel appliances and a breakfast bar. Located in a trendy neighborhood with art galleries, restaurants, and nightlife. Perfect for creative professionals or couples seeking contemporary style.',
            pricePerNight: 95,
            numGuests: 2,
            numBedrooms: 1,
            numBeds: 1,
            numBathrooms: 1,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1494203484021-3c454daf695d?w=800',
                'https://images.unsplash.com/photo-1556912173-46c336c7fd55?w=800'
            ]),
            userId: 5,
            status: 'available',
            featured: 0,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            title: 'Lakeside Family Cottage',
            description: 'Create lasting memories at this inviting lakeside cottage. Four bedrooms provide ample space for the whole family. Enjoy private lake access with a dock, kayaks included, and a fire pit for evening gatherings. The screened porch is perfect for morning coffee with lake views. Nearby activities include fishing, hiking, and exploring charming local towns. A true home away from home.',
            pricePerNight: 180,
            numGuests: 8,
            numBedrooms: 4,
            numBeds: 5,
            numBathrooms: 3,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1499696010180-025ef6e1a8f9?w=800',
                'https://images.unsplash.com/photo-1506059612708-99d6c258160e?w=800',
                'https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800'
            ]),
            userId: 1,
            status: 'available',
            featured: 0,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            title: 'Contemporary Garden Apartment',
            description: 'Relax in this ground-floor apartment with a private garden patio. The bright, airy space features modern furnishings, a fully equipped kitchen, and a cozy bedroom. The outdoor patio is perfect for al fresco dining surrounded by flowering plants. Located in a quiet residential area with easy access to public transportation and local amenities. Ideal for those seeking peaceful urban living.',
            pricePerNight: 75,
            numGuests: 2,
            numBedrooms: 1,
            numBeds: 1,
            numBathrooms: 1,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800',
                'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800',
                'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800'
            ]),
            userId: 2,
            status: 'available',
            featured: 1,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            title: 'Rustic Farmhouse Escape',
            description: 'Experience country living in this authentic farmhouse on five acres of rolling hills. Three bedrooms offer comfortable accommodations with vintage charm. The wraparound porch, large kitchen, and cozy living room with wood-burning stove create a welcoming atmosphere. Enjoy farm-fresh eggs from resident chickens, explore nature trails, and stargaze from the backyard. Perfect for a peaceful countryside retreat.',
            pricePerNight: 140,
            numGuests: 6,
            numBedrooms: 3,
            numBeds: 4,
            numBathrooms: 2,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1516156008625-3a9d6067fab5?w=800',
                'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800',
                'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=800'
            ]),
            userId: 3,
            status: 'available',
            featured: 0,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'Ski-In Ski-Out Chalet',
            description: 'Hit the slopes directly from this premium ski chalet. Located at the base of the mountain, this four-bedroom property offers true ski-in ski-out access. After a day on the mountain, relax by the stone fireplace, soak in the hot tub, or enjoy mountain views from the deck. The fully equipped kitchen and spacious living areas make this perfect for groups. Includes ski storage and boot warmers.',
            pricePerNight: 380,
            numGuests: 8,
            numBedrooms: 4,
            numBeds: 5,
            numBathrooms: 3,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1518732114903-e71d1ab99945?w=800',
                'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
                'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
                'https://images.unsplash.com/photo-1543861425-bd32b52bb6f5?w=800'
            ]),
            userId: 4,
            status: 'available',
            featured: 1,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            title: 'Art Deco City Suite',
            description: 'Experience elegance in this beautifully appointed Art Deco suite. High-end finishes, period furnishings, and modern amenities blend seamlessly. The suite features a king bedroom, marble bathroom, and a sitting area with city views. Located in a landmark building with concierge service and rooftop terrace access. Walk to theaters, museums, and fine dining. Perfect for discerning travelers.',
            pricePerNight: 195,
            numGuests: 2,
            numBedrooms: 1,
            numBeds: 1,
            numBathrooms: 1,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800',
                'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800',
                'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
                'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800'
            ]),
            userId: 5,
            status: 'available',
            featured: 0,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            title: 'Tropical Garden Bungalow',
            description: 'Immerse yourself in tropical paradise at this private bungalow surrounded by lush gardens. Two bedrooms with ceiling fans, an outdoor shower, and a hammock-adorned patio create a serene retreat. The open-air kitchen and living space blur indoor-outdoor boundaries. Just minutes from pristine beaches and local markets. Perfect for those seeking an authentic tropical experience with modern comforts.',
            pricePerNight: 110,
            numGuests: 4,
            numBedrooms: 2,
            numBeds: 2,
            numBathrooms: 1,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800',
                'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
                'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'
            ]),
            userId: 1,
            status: 'available',
            featured: 1,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            title: 'Designer Penthouse Suite',
            description: 'Live large in this stunning penthouse with panoramic city views. This two-bedroom luxury residence features floor-to-ceiling windows, a gourmet kitchen with top-of-the-line appliances, and designer furnishings throughout. The private rooftop terrace with lounge seating and outdoor kitchen is perfect for entertaining. Building amenities include gym, pool, and 24-hour security. Ultimate urban luxury living.',
            pricePerNight: 320,
            numGuests: 4,
            numBedrooms: 2,
            numBeds: 2,
            numBathrooms: 2,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=800',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
                'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'
            ]),
            userId: 2,
            status: 'available',
            featured: 0,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            title: 'Riverside Tiny House',
            description: 'Downsize to simple living in this charming tiny house on the river. Expertly designed to maximize space, this cozy retreat includes a sleeping loft, compact kitchen, and composting toilet. Large windows provide river views and natural light. The deck with seating extends your living space outdoors. Perfect for adventurous travelers seeking a unique, sustainable accommodation with a connection to nature.',
            pricePerNight: 65,
            numGuests: 2,
            numBedrooms: 0,
            numBeds: 1,
            numBathrooms: 1,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1601760562234-9814eea6663a?w=800',
                'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=800',
                'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800'
            ]),
            userId: 3,
            status: 'available',
            featured: 0,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            title: 'Mediterranean Villa with Pool',
            description: 'Enjoy la dolce vita in this elegant Mediterranean-style villa. Three bedrooms surround a central courtyard with a sparkling pool. Terracotta tiles, arched doorways, and a whitewashed exterior evoke coastal European charm. The outdoor kitchen and dining area under a pergola are perfect for long summer evenings. Olive groves and vineyard views complete the picture. An idyllic retreat for families or friends.',
            pricePerNight: 280,
            numGuests: 6,
            numBedrooms: 3,
            numBeds: 4,
            numBathrooms: 3,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
                'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800'
            ]),
            userId: 4,
            status: 'available',
            featured: 1,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            title: 'Industrial Warehouse Conversion',
            description: 'Experience unique urban living in this converted warehouse space. Soaring ceilings, exposed beams, and polished concrete floors create an impressive loft-style home. Two bedrooms with mezzanine workspace, a chef\'s kitchen, and an open living area provide flexibility. Large windows flood the space with natural light. Located in a revitalized arts district with galleries, coffee shops, and creative energy.',
            pricePerNight: 150,
            numGuests: 4,
            numBedrooms: 2,
            numBeds: 2,
            numBathrooms: 2,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800',
                'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800',
                'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800'
            ]),
            userId: 5,
            status: 'available',
            featured: 0,
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            title: 'Seaside Cottage Getaway',
            description: 'Fall asleep to ocean waves in this classic seaside cottage. This charming two-bedroom home features nautical decor, a screened porch, and a private path to the beach. The bright, coastal interior with whitewashed walls and blue accents creates a relaxing atmosphere. Outdoor shower for rinsing off sand. Walk to the pier, seafood restaurants, and beach shops. Your perfect beach escape.',
            pricePerNight: 175,
            numGuests: 4,
            numBedrooms: 2,
            numBeds: 3,
            numBathrooms: 2,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
                'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800',
                'https://images.unsplash.com/photo-1544984243-ec57ea16fe25?w=800',
                'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800'
            ]),
            userId: 1,
            status: 'available',
            featured: 0,
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            title: 'Wine Country Estate House',
            description: 'Indulge in wine country luxury at this stunning estate home. Four spacious bedrooms, each with en-suite bathrooms, accommodate groups comfortably. The gourmet kitchen opens to a great room with vaulted ceilings. Enjoy vineyard views from every window and the expansive deck. Private wine cellar, bocce court, and outdoor fireplace complete this exceptional property. Perfect for wine enthusiasts and special celebrations.',
            pricePerNight: 420,
            numGuests: 8,
            numBedrooms: 4,
            numBeds: 5,
            numBathrooms: 4,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
                'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800',
                'https://images.unsplash.com/photo-1600585152915-d208bec867a1?w=800'
            ]),
            userId: 2,
            status: 'available',
            featured: 1,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            title: 'Budget-Friendly Studio Near Campus',
            description: 'Perfect for students or short-term stays, this clean and comfortable studio offers great value. The compact space includes a kitchenette, desk area, and comfortable sleeping quarters. Located near the university campus with easy access to public transportation, libraries, and student-friendly eateries. Fast WiFi included. Simple, affordable, and convenient accommodation for academic visitors or budget travelers.',
            pricePerNight: 50,
            numGuests: 1,
            numBedrooms: 0,
            numBeds: 1,
            numBathrooms: 1,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
                'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800',
                'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800'
            ]),
            userId: 3,
            status: 'available',
            featured: 1,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            title: 'Treehouse Adventure Retreat',
            description: 'Reconnect with nature in this enchanting treehouse nestled in the forest canopy. This one-bedroom eco-retreat features sustainable design, solar power, and composting facilities. The deck suspended among the trees offers incredible forest views and bird watching opportunities. Inside, rustic charm meets modern comfort. Hiking trails begin at your doorstep. A truly unique and magical experience for nature lovers.',
            pricePerNight: 130,
            numGuests: 2,
            numBedrooms: 1,
            numBeds: 1,
            numBathrooms: 1,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
                'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800',
                'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800',
                'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800'
            ]),
            userId: 4,
            status: 'available',
            featured: 0,
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            title: 'Golf Course Luxury Home',
            description: 'Tee off from this exceptional five-bedroom home on an exclusive golf course. Panoramic fairway views from floor-to-ceiling windows and multiple patios. The open floor plan includes a gourmet kitchen, formal dining room, and luxurious living spaces. Master suite with spa-like bathroom and private balcony. Game room, home theater, and three-car garage. Resort-style pool and hot tub. Perfect for golf enthusiasts and luxury seekers.',
            pricePerNight: 500,
            numGuests: 10,
            numBedrooms: 5,
            numBeds: 6,
            numBathrooms: 4,
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800',
                'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'
            ]),
            userId: 5,
            status: 'available',
            featured: 1,
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        }
    ];

    await db.insert(listings).values(sampleListings);
    
    console.log('✅ Listings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});